CREATE TABLE mlb_data (
	year INT,
  	team VARCHAR(30) NOT NULL,
  	team_salary NUMERIC,
  	avg_player_salary NUMERIC,
  	median_player_salary NUMERIC,
	wins INT,
	cost_per_win NUMERIC,
	championship BOOLEAN
);

CREATE TABLE Salaries (
	yearID INT,
  	teamID VARCHAR(30) NOT NULL,
  	lgID VARCHAR(30) NOT NULL,
  	playerID VARCHAR(30) NOT NULL,
  	salary INT
);

CREATE TABLE Teams (
	yearID INT,
  	lgID VARCHAR(30) NOT NULL,
	teamID VARCHAR(30) NOT NULL,
  	franchID VARCHAR(30) NOT NULL,
	divID VARCHAR(30),
	Rank INT,
	G INT,
	Ghome INT,
	W INT,
	L INT,
	DivWin Boolean,
	WCWin Boolean,
	LgWin Boolean,
	WSWin Boolean,
	R INT,
	AB INT,
	H INT,
	"2B" INT,
	"3B" INT,
	HR INT,
	BB INT,
	SO INT,
	SB INT,
	CS INT,
	HBP INT,
	SF INT,
	RA INT,
	ER INT,
	ERA NUMERIC,
	CG INT,
	SHO INT,
	SV INT,
	IPouts INT,
	HA INT,
	HRA INT,
	BBA INT,
	SOA INT,
	E INT,
	DP INT,
	FP NUMERIC,
	name VARCHAR(30) NOT NULL,
	park VARCHAR(30) NOT NULL,
	attendance INT,
	BPF INT,
	PPF INT,
	teamIDBR VARCHAR(30) NOT NULL,
	teamIDlahman45 VARCHAR(30) NOT NULL,
	teamIDretro VARCHAR(30) NOT NULL
);